### ISSUE TITLE
Love this chasis

### ISSUE THREAD

**Issue by brandonssmith** [jgromes/ArduRover#1]
I found your design today and I must say I really love the idea.  I like it enough that I am going to go ahead and attempt to build my own version of it.

I am curious as to your next step as you will need to provide a base for the electronics (which I will assume with be ardurover based due to your arduino interest) and mounting points - especially keeping the power and guidance seperate.

I look forward to seeing how you progress!

**Comment by jgromes** [comment]
Thanks for the feedback, I really appreciate it :)

The electronics will be mounted in the space between the suspension pairs (on the 10 mm threaded rods). Since there are two spaces available, the electronics will be mounted in the first one and battery in the second one - both inside waterproof containers. All of this will be part of my next article on http://www.deviceplus.com so keep an eye out on the site. Hopefully, it will be published within the following month.

Let me know how your build turns out!

**Comment by jgromes** [comment]
The next article is up on the site ;)
